### ISSUE TITLE
HiGlass app crashing following search

### ISSUE THREAD

**Issue by mblanche** [higlass/higlass#612] opened 2019-04-11 17:50 UTC
_Commit_: 5a34912cc6f806f026aaa372173b2dee92ba5c19

#### Steps to reproduce
1. go to http://35.160.44.155/app
2. enter the following coordinate in the search box HanPSC8Chr10:66,602,226-140,520,348

#### Observed behavior
- App crashes and never recover
- returns in search box following string: HanPSC8Chr01:NaN-NaN & HanPSC8Chr01:NaN-NaN [offset 0,0:0,0]

#### Expected behavior
- Zooming on the coordinate

**Comment by flekschas** [comment] 2019-04-11 19:00
Thanks for reporting. Seems like the search is completely broken.

At first, I thought maybe the search string is incorrectly formatted but even when you query with the string automatically generated by HiGlass the app (1) returns `NaN` or (2) zoom to a completely different location.

**Example (1):** HiGlass parses location to `NaN`

![Apr-11-2019 14-54-56](https://user-images.githubusercontent.com/932103/55983914-365f1300-5c6a-11e9-90b6-24ccc780027b.gif)

**Example (2):** HiGlass zoom to a different location

![Apr-11-2019 14-59-32](https://user-images.githubusercontent.com/932103/55984004-758d6400-5c6a-11e9-97c6-982fefc306dc.gif)

**Comment by mblanche** [comment] 2019-04-11 20:00
Thanks Fritz for the rapid answer, let me know if I can be of any assistance.

**Comment by mblanche** [comment] 2019-04-11 20:14
Fritz, the problem seems to be with the chromosome names. Not sure if it's the JS app or the Django backend but I loaded the same data on the following server but with a chromosome reference that is just chr1 to chr17 and it fixes the bug... check it out:

http://54.245.183.83/app

thanks

**Comment by flekschas** [comment] 2019-04-11 20:28
I'd assume this is an issue with `hglib`

My assumption is that the issue is somewhere here https://github.com/higlass/higlass/blob/develop/app/scripts/SearchField.js#L60
or maybe here https://github.com/higlass/higlass/blob/develop/app/scripts/SearchField.js#L177

Although I don't see an obvious issue.

Can you revert the server (http://54.245.183.83/app) to the old issue? Then I can take a closer look later.

**Comment by mblanche** [comment] 2019-04-11 22:22
Fritz, it's a different server

http://35.160.44.155/app has the long names that breaks the app
http://54.245.183.83/app has same that but with short chromosome names fixing the search issue

**Comment by flekschas** [comment] 2019-04-11 22:42
Ah got it! :) Thanks for clarifying.

**Comment by mblanche** [comment] 2019-04-18 17:26
Fritz, is this issue resolved and closed?

**Comment by pkerpedjiev** [comment] 2019-04-18 18:27
That PR hasn't been merged because it's failing a test at the moment.

If you have a moment, perhaps you could check out that branch (`flekschas/fix-612`) and see if it resolves your issue?

**Comment by flekschas** [comment] 2019-04-18 18:29
The issue itself is fixed. Now the test needs to be fixed. Will take a look when I have time.

**Comment by mblanche** [comment] 2019-04-18 18:42
Thanks Fritz and Peter, let me know when I can merge

**Closed** 2019-04-22 01:41 UTC
Labels: bug
