### ISSUE TITLE
The last pixel of chromosomes is too large

### ISSUE THREAD

**Issue by burakalver** [higlass/higlass#779] opened 2019-09-26 20:31 UTC
_Commit_: 

#### Steps to reproduce
1. Load a cool or multivec file, zoom in anywhere other than the first chromosome such that you can see the "pixels" as large squares.

#### Expected behavior
- The pixels should align with rounded number coordinates for the given resolution, e.g. 0-1000, 1000-2000 etc.

#### Observed behavior
- The pixels are shifted to the right, e.g. 123-1123, 1123-2123 etc. This is because the last bin of every chromosome is full-bin-size in the cools and multivecs, whereas the chromsizes tracks has bp resolution. For the last chromosomes, the shift is typically multiple pixels.

**Comment by pkerpedjiev** [comment] 2019-09-27 01:37
(Copied from Slack so pardon the formatting)

That’s also actually an issue with coolers: http://higlass.io/l/?d=RAxlQSmdRbK7gAi8fpp2nQ

there’s been a longstanding discussion about how to handle this
the issue is that tiles span across chromosomes and consist of “pixels”
so imagine that you have two chromosomes that have length 500 and 300 (edited) 
and you have “pixels” (2d in the case of cooler, 1d in the case of multivec) of size 200 (edited) 
the pixels at the highest zoom level correspond to the data bins
so in the example above we have the data:

```
|-----|---|
```

And pixels

```
 11223 344
```
in an ideal world, we would display

```
 11223 445
```

but this breaks our invariant that pixels are all the same size
so what we display is, in a way, an interpolation of values fitted to a grid such that the beginning of each pixel is rendered according to the bin that it falls in

**Comment by Lmercadom** [comment] 2019-09-30 19:03
This is an example of a generated multivec (states) files. It can be observed that there are two fewer pixels between chr1 and chr2, causing a shift to the left. Chr1 ends at 249,956,422. I attach the files that I used to generate this view and the link to the view. 

Here is the link to the view:
http://54.88.112.8:8170/app/?config=UktQokcKT2CCWTSf-WPDMg

and the files:
[chrm_boundaries_test.bed.gz](https://github.com/higlass/higlass/files/3672803/chrm_boundaries_test.bed.gz)
[test_row_info.txt](https://github.com/higlass/higlass/files/3672813/test_row_info.txt)

**Comment by burakalver** [comment] 2019-09-30 19:24
In Luisa's viewconf, it looks like the shift is always 1.5-2.5 pixels to the left; it does not appear to be an issue that accumulates for the chromosomes to the right.

**Comment by alexander-veit** [comment] 2020-03-26 16:50
This issue has been addressed in https://github.com/higlass/clodius/pull/125 for multivec files. There is still a shift (see Pete's explanation above), but it should now always be less than 1 pixel.

**Closed by alexander-veit** 2020-03-26 16:50 UTC
Labels: 4DN, technical debt
