### ISSUE TITLE
chromosome grid is listed first in exported json

### ISSUE THREAD

**Issue by Chadius** [higlass/higlass#562] opened 2019-02-15 20:25 UTC
#### Steps to reproduce
1. Create a HiGlass display with a heatmap and add a 2d-chromosome-grid on the center track.
2. Select the "Export as json" option to download.
3. Download the file and drag it into the Higlass.io page. Release when it says "Drag JSON config"
4. Try to "Export as json" again

#### Observed behavior
- Page redirects to Higlass.io/app and loads the JSON
- The heatmap occludes the 2d-chromosome-grid, so the grid does not appear
- The 2d-chromosome-grid is listed before the heatmap in the json

#### Expected behavior
- Page redirects to Higlass.io/app and loads the JSON
- The 2d-chromosome-grid is drawn on top of the heatmap so the grid appears
- The 2d-chromosome-grid is listed after the heatmap in the json

I can manually edit the json file so the 2d-chromosome-grid appears after the heatmap. If I do this I get the expected behavior. My guess is either the JSON exporter or the renderer is not respecting the draw order, so the grid is always drawn first.

**Comment by flekschas** [comment] 2019-02-20 21:47
I can't reproduce this. I just tested this on higlass.io and the order of the heatmap and grid were as expected and reimporting it also worked.

Here's the example I tested: http://higlass.io/app/?config=NDY-uVsuSzCvku56TmZmiw

Could you create a test case on HiGlass.io by saving a viewconfig where the order gets inverted and share the viewconfig via an URL?

**Comment by Chadius** [comment] 2019-02-21 18:54
I've zipped Before.json and After.json.
[Archive.zip](https://github.com/higlass/higlass/files/2890664/Archive.zip)

To create Before, I visited higlass.io, followed steps 1 and 2, and then cloned another view. Here's the screenshot:
![original](https://user-images.githubusercontent.com/1376213/53193555-40a44f80-35df-11e9-9d5f-46b35bd98664.png)

I then used "Export views as JSON" and got Before.json. By dragging the file into my browser, higlass.io/app tried to load it. The chromosome grid is gone.

![dragged in](https://user-images.githubusercontent.com/1376213/53193748-ca541d00-35df-11e9-9d9f-66d0d90e3b0b.png)

I opened the json file as text and switched the orders of the center contents so the chromosome grid is listed last. I saved it as After.json. I then returned to Higlass.io (not Higlass.io/app) and dragged After.json in. Now I can see the grid.

![after edits](https://user-images.githubusercontent.com/1376213/53193885-20c15b80-35e0-11e9-9843-4d01d9fd1622.png)

**Comment by flekschas** [comment] 2019-02-21 20:36
I still can't reproduce the issue. Here's what I did:

1. Downloaded your viewconfig
2. Opened higlass.io
3. Drag-and-dropped the viewconfig (`after.json`) onto the browser tab (everything looked fine)
4. Exported the view as JSON
5. Opened a new tab with higlass.io
6. Drag-and-dropped the exported viewconfig onto the browser tab (everything looked fine)

I tried the same thing with `before.json` where I manually fixed the order of the chrom-grid and heatmap after step 3 and before step 4. Exporting and re-importing just worked fine too.

I even replicated the same view from your first screenshot, added a chrom grid, exported it, imported it and everything looked the same.

The screenshot related to "then cloned another view" doesn't show a cloned view. It shows a view that has been resized to half the width. Can you clarify what you mean?

I assume that in-between step 1 and 2 you are doing something else that causes the issue. Any chance you could record a short video showing the issue? Otherwise, I am out of ideas as I am not able to reproduce the error.

**Comment by Chadius** [comment] 2019-02-21 21:20
After.json should look correct, so go to Higlass.io and drag Before.json onto the browser. You should not see the chromosome grid. Is that what you see?

In my original bug report I followed those instructions. With the most recent comment after cloning the view I closed the cloned view, so that's why the remaining one is only half as wide.

I'll try to record a video later today to make this more clear.

**Comment by Chadius** [comment] 2019-02-21 21:26
Now I can't reproduce it - the chromosome grid is getting listed last, like it should. Is the chromosome grid always drawn last, or is it based on the JS dictionary key order? I'll keep trying to reproduce this.

**Comment by flekschas** [comment] 2019-02-23 22:07
Maybe I misunderstand the issue you are reporting. You are right, the order of the tracks in the view config matters. I.e., if you first add the chromosome grid and then add the matrix you will not see the grid. This is the case in `before.json`.

My understanding was that, given a view-config with correctly order tracks, e.g., `after.json`, you clone this view, export it as JSON, re-import, and the order is all of a sudden mixed up. The latter should not happen but if that's the case then it's a bug :) Unfortunately, I am not able to reproduce a mixup of with the track order when exporting a view as JSON but maybe I am missing a step somewhere?

**Comment by Chadius** [comment] 2019-02-28 19:46
My "steps to reproduce" are completely wrong. If you export the JSON file, the 2d-chromosome-grid is always placed last, so you won't see the problem I described. It's only if you manually change the order that it will happen. For my job I was trying to create view configurations and noticed the grid wouldn't draw based on the order of the center contents.

I can only reproduce this manual editing of the JSON file:

1. Create a HiGlass display with a heatmap and add a 2d-chromosome-grid on the center track.
2. Select the "Export as json" option to download.
3. Download the file.
4. Open the file and swap the center track's contents, so the content with "type": "2d-chromosome-grid" is listed first. Save the file.
5. Drag the edited file into the Higlass.io page. Release when it says "Drag JSON config"

So this issue might turn into "we don't expect users to manually edit JSON files". It's a much smaller issue than I thought originally.

**Comment by flekschas** [comment] 2019-02-28 20:38
Thanks for taking the time and clarifying the issue.

What you describe makes sense, and is actually expected. It's not that we don't "
don't expect users to manually edit JSON files", I do this myself all the time, but the order of tracks matters. The tracks are drawn into their location in the order they appear in the JSON file.

I'll close this issue as it's not really a bug 🙂 We could be smart about the order since there's not really a need for drawing a chromosome grid and then superimpose it entirely with a heatmap but this would require quite some work and sometimes it's actually important that the user can define the draw order (especially for 1D tracks).

Thanks for bringing this up anyway. One thing I am not sure we support yet is a simple way to swap the order of tracks through the UI without having to recreate a track. That might be something we could look into at some point.

**Closed** 2019-02-28 20:38 UTC
Labels: unclear
