### ISSUE TITLE
zoomTo does not work consistently with animateTime > 0

### ISSUE THREAD

**Issue by chen650** [higlass/higlass#296] opened 2018-08-02 19:31 UTC
_Commit_: 

#### Steps to reproduce
1. Call zoomTo with an animateTime value greater than 0. 

#### Observed behavior
-  Calling zoomTo causes the viewer to sometimes zoom to the wrong coordinates. The greater the value of animateTime, the more often that the viewer zooms to the wrong location.

#### Expected behavior
- Calling zoomTo should consistently zoom to the same coordinates.

**Comment by flekschas** [comment] 2018-08-13 14:33
@chen650 Could you provide a full example. I am unable to reproduce this error. Also which version are you using.

**Comment by mccalluc** [comment] 2018-10-23 19:27
I haven’t been able to reproduce it, and tried a variety of addresses (on and off axis), with times up to 10s. Closing.

**Closed by mccalluc** 2018-10-23 19:27 UTC
Labels: unclear
