### ISSUE TITLE
working example of on('view') or on('location') in index.html

### ISSUE THREAD

**Issue by mccalluc** [higlass/higlass#411] opened 2018-11-16 16:58 UTC
_Commit_: 82281eca077cfb372f999beafc44cfd64df70392

#### Steps to reproduce
1. Add another callback for 'location' in index.html
2. Load the page, and try interacting with it.

#### Observed behavior
- I have never seen either callback ('view' or 'location') be triggered.

#### Expected behavior
- What I'd really like would be a callback that would be triggered on *every* change to Higlass, after mouseup... but I'd be happy with a callback that is triggered on *any* change.

**Comment by flekschas** [comment] 2018-11-16 22:09
I can't reproduce the issue. The `.on('location', ...)` endpoint works as expected and `.on('view')` doesn't exist. (Did you mean `.on('viewConfig')`? See the [dev docs](http://docs-dev.higlass.io/javascript_api.html#on) for all available events.) Simple add:

```javascript
hgApi.on('location', (e) => {
  console.log('location changed', e);
});
```

to `index.html` and browse the map.

![nov-16-2018 16-57-43](https://user-images.githubusercontent.com/932103/48649505-cb622680-e9c0-11e8-86c9-a3795d0e8ada.gif)

Also, `.on('viewConfig')` already fires on _every_ change to the viewConfig but the callback is debounced.

Either way, I am closing this because there's no bug and I suggest opening a separate issue for the feature request. Feel free to re-open if there's issue I missed.

**Closed by flekschas** 2018-11-16 22:09 UTC
Labels: feature, unclear
